---
- hosts: all
  gather_facts: yes
  become_method: sudo
  become: yes
  roles:
    - role: docker-compose
      tags: docker_compose_install

    - role: prometheus-server 
      tags: prometheus_server_install
