---

global:

  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-follower-1'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - node_exporter_recording.rules
  # - node_exporter_alert.rules

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter_stats:9100']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'blackbox'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]  # Look for a HTTP 200 response.
  #   static_configs:
  #     - targets:
  #       - https://baidu.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
