---

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '192.168.56.11:9100'
        - '192.168.56.13:9100'
        - '192.168.56.14:9100'
~                                         
