---

global:

  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-leader-federation'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
    - alert.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'federate'
    scrape_interval: 10s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="node"}'
        - '{job="blackbox"}'
        # - '{__name__=~"job:.*"}'
        # - '{__name__=~"node.*"}'

    static_configs:
      - targets:
        - 'prometheus-follower-1:9090'
        - 'prometheus-follower-2:9090'

  - job_name: 'cadvisor'
    scrape_interval: 10s

    honor_labels: true
    metrics_path: 'metrics'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="node"}'
        - '{job="blackbox"}'
        # - '{__name__=~"job:.*"}'
        # - '{__name__=~"node.*"}'

    static_configs:
      - targets:
        - 'cadvisor:8080'
