---
  - name: apt update
    ansible.builtin.shell: |
            apt update

  - name: update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: install prometheus-node-exporter package
    ansible.builtin.apt:
      name: 'prometheus-node-exporter'
      state: present
